// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBikHqwIv25w9FilchoZN8oQJvE8rJP29I',
    appId: '1:923371849835:web:dfeea41ac4a5e4c91cc92e',
    messagingSenderId: '923371849835',
    projectId: 'alu-connect-b3a33',
    authDomain: 'alu-connect-b3a33.firebaseapp.com',
    storageBucket: 'alu-connect-b3a33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQrLDjAaenpGFqAVgiWxsjV3WmjVCpgMI',
    appId: '1:923371849835:android:23e15f2241f5b15b1cc92e',
    messagingSenderId: '923371849835',
    projectId: 'alu-connect-b3a33',
    storageBucket: 'alu-connect-b3a33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmE_kcBrXXryCSeuKlM6SNCn27MwDco6E',
    appId: '1:923371849835:ios:79c291c32de09b571cc92e',
    messagingSenderId: '923371849835',
    projectId: 'alu-connect-b3a33',
    storageBucket: 'alu-connect-b3a33.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmE_kcBrXXryCSeuKlM6SNCn27MwDco6E',
    appId: '1:923371849835:ios:79c291c32de09b571cc92e',
    messagingSenderId: '923371849835',
    projectId: 'alu-connect-b3a33',
    storageBucket: 'alu-connect-b3a33.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBikHqwIv25w9FilchoZN8oQJvE8rJP29I',
    appId: '1:923371849835:web:b938ccee68a5ad9f1cc92e',
    messagingSenderId: '923371849835',
    projectId: 'alu-connect-b3a33',
    authDomain: 'alu-connect-b3a33.firebaseapp.com',
    storageBucket: 'alu-connect-b3a33.firebasestorage.app',
  );
}
